#! /usr/bin/env bash

if [ ! $# -eq 3 ]; then
  echo "usage: create-merge-request <source_branch> <target_branch> <title>"
  exit 1
fi

url=https://gitlab.com/api/v4
project_id=21641725 # this could also be the url-encoded path of the project
token=$( pass cm/onepass | grep 'gitlab-access-token' | cut -d ' ' -f 2 )

source_branch=$1
target_branch=$2
title=$3

data="{ \"id\": \"$project_id\", \"source_branch\": \"$source_branch\", \"target_branch\": \"$target_branch\", \"title\": \"$title\" }"
curl --header "Authorization: Bearer $token" --header "Content-Type: application/json" --data "$data" "$url/projects/$project_id/merge_requests" | jq .web_url
