#! /usr/bin/bash

function parse_args {
  while (( "$#" )); do
    if [[ $1 == '--skip-lint' ]]; then
      skip_lint=true
    fi
    shift
  done
}

function run_linter {
  has_linter=$(yarn run 2> /dev/null | grep -q '\- lint'; echo $?)
  if [[ $skip_lint != true ]] && [[ $has_linter == "0" ]]; then
    yarn lint
    if [[ $? != "0" ]] && [[ $skip_lint != true ]]; then
      exit 1
    fi
  fi
}

function run_tests {
  yarn test && return
  exit 1
}

function push_remote {
  dir=$(pwd)
  remote_branch=$(get_remote)
  if [[ $remote_branch ]]; then
    remote_name=$(git remote)
    branch_name=$(echo $remote_branch | sed "s/$remote_name\///")
    git push origin HEAD:${branch_name}
  else
    git push origin $(git branch --show-current)
  fi
}

function list_todos {
  rg -i 'todo.*tolu'
}

parse_args "$@"
rebase $( [[ $(pwd) =~ "central-market/joe-vs" ]] && echo origin/develop )
run_linter
run_tests
push_remote
list_todos
